version: '3'


services:
  app:
    container_name: back
    build: ./backend/.
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app
  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  default:
    external:
      name: munchkin